#!/usr/bin/env bash

set -e
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
git add -A
git config user.email "ceelia0g@gmail.com"
git config user.name "Celiae"
git commit
git push -u origin master:master
