import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const data = [
    {
      title: "My Blog - Ceblog",
      link: "https://ceblog.vercel.app",
    },
    {
      title: "My Github Page - celiae",
      link: "https://ceblog.vercel.app",
    },
  ];
  const jump = (link: string) => {
    router.push(link);
  };
  return (
    <>
      <Head>
        <title>Celiae Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10 px-20 bg-slate-200">
        <h1 className="text-2xl font-bold">Welcome</h1>
        <h2 className="text-lg mb-10">Hi! This is Celiae</h2>
        Links:
        <div className="grid place-items-center gap-3 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {data.map((d, index) => (
            <div
              key={index}
              className="bg-gradient-to-r w-full p-3 px-10 m-3 cursor-pointer from-cyan-300 to-blue-300
               hover:from-cyan-500 hover:to-blue-500 duration-150"
              onClick={() => {
                jump(d.link);
              }}
            >
              <h1 className="text-xl">{d.title}</h1>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
